package lab1_exceptions;

import java.io.IOException;

public class ExceptionsLab1 {

	public static void main(String[] args) {
		
		String a = testMethodA();
		System.out.println(a);
		
		System.out.println();
		
		String b = testMethodB();
		System.out.println(b);
		
		System.out.println();
		
		String c = testMethodC();
		System.out.println(c);
		
		System.out.println();
		
		String d = testMethodD();
		System.out.println(d);
		
		System.out.println();
		
		

	}


public static String testMethodA(){
	try{
		return "Method A";
	}
	catch (Exception e){
		return "Catch Exception: " + e;
	}
	finally{
		return "OK from finally";
	}
}

public static String testMethodB(){
	try{
		return "Method B";
	}
	catch (Exception e){
		return "Exception: " + e;
	}
	finally{
		 System.out.println("Finally section");
	}
}

public static String testMethodC(){
	try{
		return "Method C";
	}
	catch (Exception e){
		return "Exception: " + e;
	}
	finally {
		return "Finally";
	}
}


public static String testMethodD() throws IOException{
	try{
		return "Method D";
	}
	catch (Exception e){
		return "Exception: " + e;
	}
	finally{
		return "Finally";
	}
}
}
